use customer_behavior;
SELECT * FROM customer LIMIT 5;



-- Q1. What is the total revenue generated by male vs. female customers?

select gender, SUM(purchase_amount) AS total_revenue
from customer
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, purchase_amount
from customer
where discount_applied='yes' AND purchase_amount >= (select AVG(purchase_amount) from customer);


-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, Round(avg(review_rating),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type, AVG(purchase_amount) AS avg_pur_amount
from customer
where shipping_type IN ('Standard','Express')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.

select subscription_status, 
COUNT(customer_id) AS total_customers, 
AVG(purchase_amount) AS avg_spend,
SUM(purchase_amount) AS total_revenue
from customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
 ROUND(
        SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) 
        / COUNT(*) * 100, 2
    ) AS pct_discount
from customer
GROUP BY item_purchased
ORDER BY pct_discount DESC LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

WITH customer_type AS(
 select customer_id, previous_purchases,
   CASE 
      WHEN previous_purchases = 1 THEN 'NEW'
      WHEN previous_purchases BETWEEN 2 AND 10  THEN 'Returning'
      ELSE 'Loyal'
	END AS customer_segment
 from customer
)
select customer_segment, count(*) as total_customers
from customer_type 
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category? 

WITH Ranked_products AS
(
   select item_purchased,
          category,
          COUNT(customer_id) AS total_orders,
       Row_Number() OVER (PARTITION BY category ORDER BY count(customer_id) DESC) AS rnk
       from customer
       GROUP BY category, item_purchased
       )
       
       select total_orders,item_purchased,rnk, category
       from ranked_products
       where rnk <= 3;
 
 
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?       

-- select Count(customer_id) AS total_orders,
--        subscription_status,
--        Round(count(customer_id)*100/ (select count(*) from customer where previous_purchases > 5 ),2) AS pct
-- from customer
-- where previous_purchases > 5
-- GROUP BY subscription_status;

select Count(*) AS total_orders,
       subscription_status,
       Round(count(*)*100/ SUM(count(*)) OVER(), 
       2) AS pct
from customer
where previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group? 

select age_groups,
SUM(purchase_amount) AS total_age_revenue,
ROUND (
SUM(purchase_amount)*100.0 / SUM(SUM(purchase_amount)) OVER(),
2) AS rev_per
from customer
GROUP BY age_groups;

-- Q11. -- WHAT: Total revenue for every month across all years
--  This is the #1 chart in every financial dashboard

SELECT 
    DATE_FORMAT(purchase_date, '%Y-%b') AS month_label,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY month_label
ORDER BY total_revenue DESC;

-- Q12 Revenue grouped by quarter (Q1, Q2, Q3, Q4)
--  Quarterly analysis is standard in all financial reporting
 
SELECT
    purchase_year,
    purchase_quarter,
    CONCAT('Q', purchase_quarter, ' ', purchase_year) AS quarter_label,
    COUNT(*)               AS total_orders,
    SUM(purchase_amount)   AS total_revenue,
    COUNT(DISTINCT customer_id) AS unique_customers
FROM customer
GROUP BY purchase_year, purchase_quarter
ORDER BY purchase_year, purchase_quarter;


-- Q13 Which season performs best in terms of revenue, orders, customer satisfaction, and 
-- how many of those customers are subscribers?
-- Retail businesses plan inventory and promotions by season

SELECT
    season,
    COUNT(*)                            AS total_orders,
    SUM(purchase_amount)                AS total_revenue,
    ROUND(AVG(purchase_amount), 2)      AS avg_purchase,
    ROUND(AVG(review_rating), 2)        AS avg_rating,
    COUNT(CASE WHEN subscription_status = 'Yes'
               THEN 1 END)             AS subscribed_customers
FROM customer
GROUP BY season
ORDER BY total_revenue DESC;


-- Q14 Month-over-Month Revenue Growth ( Revenue change from previous month to current month)

WITH monthly_revenue AS (
    SELECT
        YEAR(purchase_date) AS purchase_year,
        MONTH(purchase_date) AS purchase_month,
        DATE_FORMAT(purchase_date, '%b %Y') AS month_label,
        SUM(purchase_amount) AS revenue
    FROM customer
    GROUP BY
        YEAR(purchase_date),
        MONTH(purchase_date),
        DATE_FORMAT(purchase_date, '%b %Y')
)

SELECT
    month_label,
    revenue AS current_revenue,
    LAG(revenue) OVER (ORDER BY purchase_year, purchase_month) AS prev_month_revenue,
    ROUND(
        (revenue - LAG(revenue) OVER (ORDER BY purchase_year, purchase_month))
        / NULLIF(LAG(revenue) OVER (ORDER BY purchase_year, purchase_month), 0)
        * 100,
    2) AS mom_pct_change
FROM monthly_revenue
ORDER BY purchase_year, purchase_month;


-- Q15 - Running / Cumulative Revenue 
-- Month-wise revenue and total revenue accumulated from the beginning till each month

WITH monthly_revenue AS (
    SELECT
        YEAR(purchase_date) AS purchase_year,
        MONTH(purchase_date) AS purchase_month,
        DATE_FORMAT(purchase_date, '%b %Y') AS month_label,
        SUM(purchase_amount) AS monthly_revenue
    FROM customer
    GROUP BY
        YEAR(purchase_date),
        MONTH(purchase_date),
        DATE_FORMAT(purchase_date, '%b %Y')
)

SELECT
    month_label,
    monthly_revenue,
    SUM(monthly_revenue) OVER (
        ORDER BY purchase_year, purchase_month
    ) AS cumulative_revenue
FROM monthly_revenue
ORDER BY purchase_year, purchase_month;


-- Q16 - What is the average revenue over the last 3 months (including current month)?

	SELECT
    purchase_year,
    purchase_month,
    SUM(purchase_amount) AS monthly_revenue,
    ROUND(
        AVG(SUM(purchase_amount)) OVER (
            ORDER BY purchase_year, purchase_month
            ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),
    2) AS rolling_3m_avg
FROM customer
GROUP BY purchase_year, purchase_month
ORDER BY purchase_year, purchase_month;


-- Q17 - Do customers behave differently on weekdays vs weekends?

SELECT
    purchase_day_name                   AS day_of_week,
    is_weekend,
    COUNT(*)                            AS total_orders,
    SUM(purchase_amount)                AS total_revenue,
    ROUND(AVG(purchase_amount), 2)      AS avg_order_value,
    ROUND(AVG(review_rating), 2)        AS avg_rating
FROM customer
GROUP BY purchase_day_name, is_weekend
ORDER BY
    CASE purchase_day_name
        WHEN 'Monday'    THEN 1
        WHEN 'Tuesday'   THEN 2
        WHEN 'Wednesday' THEN 3
        WHEN 'Thursday'  THEN 4
        WHEN 'Friday'    THEN 5
        WHEN 'Saturday'  THEN 6
        WHEN 'Sunday'    THEN 7
    END;
    
    
-- Q18 Year-over-Year Revenue by Category
 
select category,
	   purchase_year,
       COUNT(*)                            AS total_orders,
    SUM(purchase_amount)                AS total_revenue,
    ROUND(AVG(purchase_amount), 2)      AS avg_order_value,
    ROUND(AVG(review_rating), 2)        AS avg_rating,
    RANK() OVER(
           PARTITION BY purchase_year ORDER BY SUM(purchase_amount) DESC 
           ) AS yearwise_rev_rnk
           
from customer
GROUP BY purchase_year, category
ORDER BY yearwise_rev_rnk, purchase_year;

-- Q19 Who are our most valuable customers who purchased recently?

SELECT
    customer_id,
    age_groups,
    gender,
    purchase_date,
    purchase_amount,
    spend_segment,
    days_since_purchase,
    estimated_annual_value,
    -- Label each customer
    CASE
        WHEN days_since_purchase <= 30  AND spend_segment = 'Premium ($81-100)'
             THEN 'VIP — Recent Premium'
        WHEN days_since_purchase <= 60  AND purchase_amount > 60
             THEN 'High Value — Active'
        WHEN days_since_purchase > 180
             THEN 'At Risk — Not Seen Recently'
        ELSE 'Regular Customer'
    END AS customer_segment
FROM customer
ORDER BY estimated_annual_value DESC, days_since_purchase ASC
LIMIT 20;

 
    
    
    
    
    
    
    
    